# Generated by Django 6.0.2 on 2026-04-02 10:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(max_length=255)),
                ('scope_type', models.CharField(choices=[('oob', 'Out-of-Box'), ('tenant', 'Tenant'), ('user', 'User')], max_length=10)),
                ('scope_id', models.CharField(blank=True, max_length=255, null=True)),
                ('release_version', models.CharField(max_length=50)),
                ('base_config_id', models.UUIDField(blank=True, null=True)),
                ('base_release_version', models.CharField(blank=True, max_length=50, null=True)),
                ('base_config_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('parent_config_instance_id', models.UUIDField(blank=True, null=True)),
                ('config_json', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'config_instances',
                'indexes': [models.Index(fields=['config_key', 'scope_type', 'scope_id', 'is_active'], name='idx_config_lookup'), models.Index(fields=['release_version'], name='idx_release'), models.Index(fields=['base_config_id'], name='idx_base_config')],
                'unique_together': {('config_key', 'scope_type', 'scope_id', 'is_active')},
            },
        ),
    ]
