# Generated by Django 5.0.6 on 2026-04-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configinstance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='configinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('config_key', 'scope_type', 'scope_id'), name='unique_active_config'),
        ),
        migrations.AddConstraint(
            model_name='configinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'oob')), fields=('config_key', 'release_version'), name='unique_oob_config'),
        ),
    ]
